/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as RTokenIndexRouteImport } from './routes/r.$token.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as RTokenSplatRouteImport } from './routes/r.$token.$'
import { Route as AuthenticatedAppBusinessBriefRouteImport } from './routes/_authenticated/app.business-brief'
import { Route as AuthenticatedAppBookCallRouteImport } from './routes/_authenticated/app.book-call'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app.admin.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicRValidateRouteImport } from './routes/api/public/r/validate'
import { Route as ApiPublicRStateRouteImport } from './routes/api/public/r/state'
import { Route as ApiPublicRSaveRouteImport } from './routes/api/public/r/save'
import { Route as ApiPublicRCompleteRouteImport } from './routes/api/public/r/complete'
import { Route as ApiPublicRCaptureRouteImport } from './routes/api/public/r/capture'
import { Route as AuthenticatedAppAdminWillAiRouteImport } from './routes/_authenticated/app.admin.will-ai'
import { Route as AuthenticatedAppAdminSopsRouteImport } from './routes/_authenticated/app.admin.sops'
import { Route as AuthenticatedAppAdminReviewRouteImport } from './routes/_authenticated/app.admin.review'
import { Route as AuthenticatedAppAdminSopsIndexRouteImport } from './routes/_authenticated/app.admin.sops.index'
import { Route as AuthenticatedAppToolsKeySplatRouteImport } from './routes/_authenticated/app.tools.$key.$'
import { Route as AuthenticatedAppAdminReviewOwnerIdRouteImport } from './routes/_authenticated/app.admin.review.$ownerId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenIndexRoute = RTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RTokenRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RTokenSplatRoute = RTokenSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => RTokenRoute,
} as any)
const AuthenticatedAppBusinessBriefRoute =
  AuthenticatedAppBusinessBriefRouteImport.update({
    id: '/app/business-brief',
    path: '/app/business-brief',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBookCallRoute =
  AuthenticatedAppBookCallRouteImport.update({
    id: '/app/book-call',
    path: '/app/book-call',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRValidateRoute = ApiPublicRValidateRouteImport.update({
  id: '/api/public/r/validate',
  path: '/api/public/r/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRStateRoute = ApiPublicRStateRouteImport.update({
  id: '/api/public/r/state',
  path: '/api/public/r/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRSaveRoute = ApiPublicRSaveRouteImport.update({
  id: '/api/public/r/save',
  path: '/api/public/r/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRCompleteRoute = ApiPublicRCompleteRouteImport.update({
  id: '/api/public/r/complete',
  path: '/api/public/r/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRCaptureRoute = ApiPublicRCaptureRouteImport.update({
  id: '/api/public/r/capture',
  path: '/api/public/r/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppAdminWillAiRoute =
  AuthenticatedAppAdminWillAiRouteImport.update({
    id: '/will-ai',
    path: '/will-ai',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminSopsRoute =
  AuthenticatedAppAdminSopsRouteImport.update({
    id: '/sops',
    path: '/sops',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminReviewRoute =
  AuthenticatedAppAdminReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminSopsIndexRoute =
  AuthenticatedAppAdminSopsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdminSopsRoute,
  } as any)
const AuthenticatedAppToolsKeySplatRoute =
  AuthenticatedAppToolsKeySplatRouteImport.update({
    id: '/app/tools/$key/$',
    path: '/app/tools/$key/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminReviewOwnerIdRoute =
  AuthenticatedAppAdminReviewOwnerIdRouteImport.update({
    id: '/$ownerId',
    path: '/$ownerId',
    getParentRoute: () => AuthenticatedAppAdminReviewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/r/$token': typeof RTokenRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/book-call': typeof AuthenticatedAppBookCallRoute
  '/app/business-brief': typeof AuthenticatedAppBusinessBriefRoute
  '/r/$token/$': typeof RTokenSplatRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/r/$token/': typeof RTokenIndexRoute
  '/app/admin/review': typeof AuthenticatedAppAdminReviewRouteWithChildren
  '/app/admin/sops': typeof AuthenticatedAppAdminSopsRouteWithChildren
  '/app/admin/will-ai': typeof AuthenticatedAppAdminWillAiRoute
  '/api/public/r/capture': typeof ApiPublicRCaptureRoute
  '/api/public/r/complete': typeof ApiPublicRCompleteRoute
  '/api/public/r/save': typeof ApiPublicRSaveRoute
  '/api/public/r/state': typeof ApiPublicRStateRoute
  '/api/public/r/validate': typeof ApiPublicRValidateRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/admin/review/$ownerId': typeof AuthenticatedAppAdminReviewOwnerIdRoute
  '/app/tools/$key/$': typeof AuthenticatedAppToolsKeySplatRoute
  '/app/admin/sops/': typeof AuthenticatedAppAdminSopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/book-call': typeof AuthenticatedAppBookCallRoute
  '/app/business-brief': typeof AuthenticatedAppBusinessBriefRoute
  '/r/$token/$': typeof RTokenSplatRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/r/$token': typeof RTokenIndexRoute
  '/app/admin/review': typeof AuthenticatedAppAdminReviewRouteWithChildren
  '/app/admin/will-ai': typeof AuthenticatedAppAdminWillAiRoute
  '/api/public/r/capture': typeof ApiPublicRCaptureRoute
  '/api/public/r/complete': typeof ApiPublicRCompleteRoute
  '/api/public/r/save': typeof ApiPublicRSaveRoute
  '/api/public/r/state': typeof ApiPublicRStateRoute
  '/api/public/r/validate': typeof ApiPublicRValidateRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/admin/review/$ownerId': typeof AuthenticatedAppAdminReviewOwnerIdRoute
  '/app/tools/$key/$': typeof AuthenticatedAppToolsKeySplatRoute
  '/app/admin/sops': typeof AuthenticatedAppAdminSopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/r/$token': typeof RTokenRouteWithChildren
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/book-call': typeof AuthenticatedAppBookCallRoute
  '/_authenticated/app/business-brief': typeof AuthenticatedAppBusinessBriefRoute
  '/r/$token/$': typeof RTokenSplatRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/r/$token/': typeof RTokenIndexRoute
  '/_authenticated/app/admin/review': typeof AuthenticatedAppAdminReviewRouteWithChildren
  '/_authenticated/app/admin/sops': typeof AuthenticatedAppAdminSopsRouteWithChildren
  '/_authenticated/app/admin/will-ai': typeof AuthenticatedAppAdminWillAiRoute
  '/api/public/r/capture': typeof ApiPublicRCaptureRoute
  '/api/public/r/complete': typeof ApiPublicRCompleteRoute
  '/api/public/r/save': typeof ApiPublicRSaveRoute
  '/api/public/r/state': typeof ApiPublicRStateRoute
  '/api/public/r/validate': typeof ApiPublicRValidateRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/admin/review/$ownerId': typeof AuthenticatedAppAdminReviewOwnerIdRoute
  '/_authenticated/app/tools/$key/$': typeof AuthenticatedAppToolsKeySplatRoute
  '/_authenticated/app/admin/sops/': typeof AuthenticatedAppAdminSopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/r/$token'
    | '/app/admin'
    | '/app/book-call'
    | '/app/business-brief'
    | '/r/$token/$'
    | '/app/'
    | '/r/$token/'
    | '/app/admin/review'
    | '/app/admin/sops'
    | '/app/admin/will-ai'
    | '/api/public/r/capture'
    | '/api/public/r/complete'
    | '/api/public/r/save'
    | '/api/public/r/state'
    | '/api/public/r/validate'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/app/admin/'
    | '/app/admin/review/$ownerId'
    | '/app/tools/$key/$'
    | '/app/admin/sops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/book-call'
    | '/app/business-brief'
    | '/r/$token/$'
    | '/app'
    | '/r/$token'
    | '/app/admin/review'
    | '/app/admin/will-ai'
    | '/api/public/r/capture'
    | '/api/public/r/complete'
    | '/api/public/r/save'
    | '/api/public/r/state'
    | '/api/public/r/validate'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/app/admin'
    | '/app/admin/review/$ownerId'
    | '/app/tools/$key/$'
    | '/app/admin/sops'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/r/$token'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/book-call'
    | '/_authenticated/app/business-brief'
    | '/r/$token/$'
    | '/_authenticated/app/'
    | '/r/$token/'
    | '/_authenticated/app/admin/review'
    | '/_authenticated/app/admin/sops'
    | '/_authenticated/app/admin/will-ai'
    | '/api/public/r/capture'
    | '/api/public/r/complete'
    | '/api/public/r/save'
    | '/api/public/r/state'
    | '/api/public/r/validate'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/admin/review/$ownerId'
    | '/_authenticated/app/tools/$key/$'
    | '/_authenticated/app/admin/sops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RTokenRoute: typeof RTokenRouteWithChildren
  ApiPublicRCaptureRoute: typeof ApiPublicRCaptureRoute
  ApiPublicRCompleteRoute: typeof ApiPublicRCompleteRoute
  ApiPublicRSaveRoute: typeof ApiPublicRSaveRoute
  ApiPublicRStateRoute: typeof ApiPublicRStateRoute
  ApiPublicRValidateRoute: typeof ApiPublicRValidateRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token/': {
      id: '/r/$token/'
      path: '/'
      fullPath: '/r/$token/'
      preLoaderRoute: typeof RTokenIndexRouteImport
      parentRoute: typeof RTokenRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/r/$token/$': {
      id: '/r/$token/$'
      path: '/$'
      fullPath: '/r/$token/$'
      preLoaderRoute: typeof RTokenSplatRouteImport
      parentRoute: typeof RTokenRoute
    }
    '/_authenticated/app/business-brief': {
      id: '/_authenticated/app/business-brief'
      path: '/app/business-brief'
      fullPath: '/app/business-brief'
      preLoaderRoute: typeof AuthenticatedAppBusinessBriefRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/book-call': {
      id: '/_authenticated/app/book-call'
      path: '/app/book-call'
      fullPath: '/app/book-call'
      preLoaderRoute: typeof AuthenticatedAppBookCallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/validate': {
      id: '/api/public/r/validate'
      path: '/api/public/r/validate'
      fullPath: '/api/public/r/validate'
      preLoaderRoute: typeof ApiPublicRValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/state': {
      id: '/api/public/r/state'
      path: '/api/public/r/state'
      fullPath: '/api/public/r/state'
      preLoaderRoute: typeof ApiPublicRStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/save': {
      id: '/api/public/r/save'
      path: '/api/public/r/save'
      fullPath: '/api/public/r/save'
      preLoaderRoute: typeof ApiPublicRSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/complete': {
      id: '/api/public/r/complete'
      path: '/api/public/r/complete'
      fullPath: '/api/public/r/complete'
      preLoaderRoute: typeof ApiPublicRCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/capture': {
      id: '/api/public/r/capture'
      path: '/api/public/r/capture'
      fullPath: '/api/public/r/capture'
      preLoaderRoute: typeof ApiPublicRCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/admin/will-ai': {
      id: '/_authenticated/app/admin/will-ai'
      path: '/will-ai'
      fullPath: '/app/admin/will-ai'
      preLoaderRoute: typeof AuthenticatedAppAdminWillAiRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/sops': {
      id: '/_authenticated/app/admin/sops'
      path: '/sops'
      fullPath: '/app/admin/sops'
      preLoaderRoute: typeof AuthenticatedAppAdminSopsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/review': {
      id: '/_authenticated/app/admin/review'
      path: '/review'
      fullPath: '/app/admin/review'
      preLoaderRoute: typeof AuthenticatedAppAdminReviewRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/sops/': {
      id: '/_authenticated/app/admin/sops/'
      path: '/'
      fullPath: '/app/admin/sops/'
      preLoaderRoute: typeof AuthenticatedAppAdminSopsIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminSopsRoute
    }
    '/_authenticated/app/tools/$key/$': {
      id: '/_authenticated/app/tools/$key/$'
      path: '/app/tools/$key/$'
      fullPath: '/app/tools/$key/$'
      preLoaderRoute: typeof AuthenticatedAppToolsKeySplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/review/$ownerId': {
      id: '/_authenticated/app/admin/review/$ownerId'
      path: '/$ownerId'
      fullPath: '/app/admin/review/$ownerId'
      preLoaderRoute: typeof AuthenticatedAppAdminReviewOwnerIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminReviewRoute
    }
  }
}

interface AuthenticatedAppAdminReviewRouteChildren {
  AuthenticatedAppAdminReviewOwnerIdRoute: typeof AuthenticatedAppAdminReviewOwnerIdRoute
}

const AuthenticatedAppAdminReviewRouteChildren: AuthenticatedAppAdminReviewRouteChildren =
  {
    AuthenticatedAppAdminReviewOwnerIdRoute:
      AuthenticatedAppAdminReviewOwnerIdRoute,
  }

const AuthenticatedAppAdminReviewRouteWithChildren =
  AuthenticatedAppAdminReviewRoute._addFileChildren(
    AuthenticatedAppAdminReviewRouteChildren,
  )

interface AuthenticatedAppAdminSopsRouteChildren {
  AuthenticatedAppAdminSopsIndexRoute: typeof AuthenticatedAppAdminSopsIndexRoute
}

const AuthenticatedAppAdminSopsRouteChildren: AuthenticatedAppAdminSopsRouteChildren =
  {
    AuthenticatedAppAdminSopsIndexRoute: AuthenticatedAppAdminSopsIndexRoute,
  }

const AuthenticatedAppAdminSopsRouteWithChildren =
  AuthenticatedAppAdminSopsRoute._addFileChildren(
    AuthenticatedAppAdminSopsRouteChildren,
  )

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminReviewRoute: typeof AuthenticatedAppAdminReviewRouteWithChildren
  AuthenticatedAppAdminSopsRoute: typeof AuthenticatedAppAdminSopsRouteWithChildren
  AuthenticatedAppAdminWillAiRoute: typeof AuthenticatedAppAdminWillAiRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminReviewRoute:
    AuthenticatedAppAdminReviewRouteWithChildren,
  AuthenticatedAppAdminSopsRoute: AuthenticatedAppAdminSopsRouteWithChildren,
  AuthenticatedAppAdminWillAiRoute: AuthenticatedAppAdminWillAiRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppBookCallRoute: typeof AuthenticatedAppBookCallRoute
  AuthenticatedAppBusinessBriefRoute: typeof AuthenticatedAppBusinessBriefRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppToolsKeySplatRoute: typeof AuthenticatedAppToolsKeySplatRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppBookCallRoute: AuthenticatedAppBookCallRoute,
  AuthenticatedAppBusinessBriefRoute: AuthenticatedAppBusinessBriefRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppToolsKeySplatRoute: AuthenticatedAppToolsKeySplatRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RTokenRouteChildren {
  RTokenSplatRoute: typeof RTokenSplatRoute
  RTokenIndexRoute: typeof RTokenIndexRoute
}

const RTokenRouteChildren: RTokenRouteChildren = {
  RTokenSplatRoute: RTokenSplatRoute,
  RTokenIndexRoute: RTokenIndexRoute,
}

const RTokenRouteWithChildren =
  RTokenRoute._addFileChildren(RTokenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RTokenRoute: RTokenRouteWithChildren,
  ApiPublicRCaptureRoute: ApiPublicRCaptureRoute,
  ApiPublicRCompleteRoute: ApiPublicRCompleteRoute,
  ApiPublicRSaveRoute: ApiPublicRSaveRoute,
  ApiPublicRStateRoute: ApiPublicRStateRoute,
  ApiPublicRValidateRoute: ApiPublicRValidateRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
