/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as RTokenIndexRouteImport } from './routes/r.$token.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as RTokenSplatRouteImport } from './routes/r.$token.$'
import { Route as AuthenticatedAppBookCallRouteImport } from './routes/_authenticated/app.book-call'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app.admin.index'
import { Route as ApiPublicRValidateRouteImport } from './routes/api/public/r/validate'
import { Route as ApiPublicRStateRouteImport } from './routes/api/public/r/state'
import { Route as ApiPublicRSaveRouteImport } from './routes/api/public/r/save'
import { Route as ApiPublicRCompleteRouteImport } from './routes/api/public/r/complete'
import { Route as ApiPublicRCaptureRouteImport } from './routes/api/public/r/capture'
import { Route as AuthenticatedAppAdminReviewRouteImport } from './routes/_authenticated/app.admin.review'
import { Route as AuthenticatedAppAdminSalescodeIndexRouteImport } from './routes/_authenticated/app.admin.salescode.index'
import { Route as AuthenticatedAppAdminAuditIndexRouteImport } from './routes/_authenticated/app.admin.audit.index'
import { Route as AuthenticatedAppToolsKeySplatRouteImport } from './routes/_authenticated/app.tools.$key.$'
import { Route as AuthenticatedAppAdminSalescodeOwnerIdRouteImport } from './routes/_authenticated/app.admin.salescode.$ownerId'
import { Route as AuthenticatedAppAdminAuditOwnerIdRouteImport } from './routes/_authenticated/app.admin.audit.$ownerId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenIndexRoute = RTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RTokenRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RTokenSplatRoute = RTokenSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => RTokenRoute,
} as any)
const AuthenticatedAppBookCallRoute =
  AuthenticatedAppBookCallRouteImport.update({
    id: '/app/book-call',
    path: '/app/book-call',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const ApiPublicRValidateRoute = ApiPublicRValidateRouteImport.update({
  id: '/api/public/r/validate',
  path: '/api/public/r/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRStateRoute = ApiPublicRStateRouteImport.update({
  id: '/api/public/r/state',
  path: '/api/public/r/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRSaveRoute = ApiPublicRSaveRouteImport.update({
  id: '/api/public/r/save',
  path: '/api/public/r/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRCompleteRoute = ApiPublicRCompleteRouteImport.update({
  id: '/api/public/r/complete',
  path: '/api/public/r/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRCaptureRoute = ApiPublicRCaptureRouteImport.update({
  id: '/api/public/r/capture',
  path: '/api/public/r/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppAdminReviewRoute =
  AuthenticatedAppAdminReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminSalescodeIndexRoute =
  AuthenticatedAppAdminSalescodeIndexRouteImport.update({
    id: '/salescode/',
    path: '/salescode/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminAuditIndexRoute =
  AuthenticatedAppAdminAuditIndexRouteImport.update({
    id: '/audit/',
    path: '/audit/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppToolsKeySplatRoute =
  AuthenticatedAppToolsKeySplatRouteImport.update({
    id: '/app/tools/$key/$',
    path: '/app/tools/$key/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminSalescodeOwnerIdRoute =
  AuthenticatedAppAdminSalescodeOwnerIdRouteImport.update({
    id: '/salescode/$ownerId',
    path: '/salescode/$ownerId',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminAuditOwnerIdRoute =
  AuthenticatedAppAdminAuditOwnerIdRouteImport.update({
    id: '/audit/$ownerId',
    path: '/audit/$ownerId',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/r/$token': typeof RTokenRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/book-call': typeof AuthenticatedAppBookCallRoute
  '/r/$token/$': typeof RTokenSplatRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/r/$token/': typeof RTokenIndexRoute
  '/app/admin/review': typeof AuthenticatedAppAdminReviewRoute
  '/api/public/r/capture': typeof ApiPublicRCaptureRoute
  '/api/public/r/complete': typeof ApiPublicRCompleteRoute
  '/api/public/r/save': typeof ApiPublicRSaveRoute
  '/api/public/r/state': typeof ApiPublicRStateRoute
  '/api/public/r/validate': typeof ApiPublicRValidateRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/admin/audit/$ownerId': typeof AuthenticatedAppAdminAuditOwnerIdRoute
  '/app/admin/salescode/$ownerId': typeof AuthenticatedAppAdminSalescodeOwnerIdRoute
  '/app/tools/$key/$': typeof AuthenticatedAppToolsKeySplatRoute
  '/app/admin/audit/': typeof AuthenticatedAppAdminAuditIndexRoute
  '/app/admin/salescode/': typeof AuthenticatedAppAdminSalescodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/book-call': typeof AuthenticatedAppBookCallRoute
  '/r/$token/$': typeof RTokenSplatRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/r/$token': typeof RTokenIndexRoute
  '/app/admin/review': typeof AuthenticatedAppAdminReviewRoute
  '/api/public/r/capture': typeof ApiPublicRCaptureRoute
  '/api/public/r/complete': typeof ApiPublicRCompleteRoute
  '/api/public/r/save': typeof ApiPublicRSaveRoute
  '/api/public/r/state': typeof ApiPublicRStateRoute
  '/api/public/r/validate': typeof ApiPublicRValidateRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/admin/audit/$ownerId': typeof AuthenticatedAppAdminAuditOwnerIdRoute
  '/app/admin/salescode/$ownerId': typeof AuthenticatedAppAdminSalescodeOwnerIdRoute
  '/app/tools/$key/$': typeof AuthenticatedAppToolsKeySplatRoute
  '/app/admin/audit': typeof AuthenticatedAppAdminAuditIndexRoute
  '/app/admin/salescode': typeof AuthenticatedAppAdminSalescodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/r/$token': typeof RTokenRouteWithChildren
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/book-call': typeof AuthenticatedAppBookCallRoute
  '/r/$token/$': typeof RTokenSplatRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/r/$token/': typeof RTokenIndexRoute
  '/_authenticated/app/admin/review': typeof AuthenticatedAppAdminReviewRoute
  '/api/public/r/capture': typeof ApiPublicRCaptureRoute
  '/api/public/r/complete': typeof ApiPublicRCompleteRoute
  '/api/public/r/save': typeof ApiPublicRSaveRoute
  '/api/public/r/state': typeof ApiPublicRStateRoute
  '/api/public/r/validate': typeof ApiPublicRValidateRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/admin/audit/$ownerId': typeof AuthenticatedAppAdminAuditOwnerIdRoute
  '/_authenticated/app/admin/salescode/$ownerId': typeof AuthenticatedAppAdminSalescodeOwnerIdRoute
  '/_authenticated/app/tools/$key/$': typeof AuthenticatedAppToolsKeySplatRoute
  '/_authenticated/app/admin/audit/': typeof AuthenticatedAppAdminAuditIndexRoute
  '/_authenticated/app/admin/salescode/': typeof AuthenticatedAppAdminSalescodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/r/$token'
    | '/app/admin'
    | '/app/book-call'
    | '/r/$token/$'
    | '/app/'
    | '/r/$token/'
    | '/app/admin/review'
    | '/api/public/r/capture'
    | '/api/public/r/complete'
    | '/api/public/r/save'
    | '/api/public/r/state'
    | '/api/public/r/validate'
    | '/app/admin/'
    | '/app/admin/audit/$ownerId'
    | '/app/admin/salescode/$ownerId'
    | '/app/tools/$key/$'
    | '/app/admin/audit/'
    | '/app/admin/salescode/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/book-call'
    | '/r/$token/$'
    | '/app'
    | '/r/$token'
    | '/app/admin/review'
    | '/api/public/r/capture'
    | '/api/public/r/complete'
    | '/api/public/r/save'
    | '/api/public/r/state'
    | '/api/public/r/validate'
    | '/app/admin'
    | '/app/admin/audit/$ownerId'
    | '/app/admin/salescode/$ownerId'
    | '/app/tools/$key/$'
    | '/app/admin/audit'
    | '/app/admin/salescode'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/r/$token'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/book-call'
    | '/r/$token/$'
    | '/_authenticated/app/'
    | '/r/$token/'
    | '/_authenticated/app/admin/review'
    | '/api/public/r/capture'
    | '/api/public/r/complete'
    | '/api/public/r/save'
    | '/api/public/r/state'
    | '/api/public/r/validate'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/admin/audit/$ownerId'
    | '/_authenticated/app/admin/salescode/$ownerId'
    | '/_authenticated/app/tools/$key/$'
    | '/_authenticated/app/admin/audit/'
    | '/_authenticated/app/admin/salescode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RTokenRoute: typeof RTokenRouteWithChildren
  ApiPublicRCaptureRoute: typeof ApiPublicRCaptureRoute
  ApiPublicRCompleteRoute: typeof ApiPublicRCompleteRoute
  ApiPublicRSaveRoute: typeof ApiPublicRSaveRoute
  ApiPublicRStateRoute: typeof ApiPublicRStateRoute
  ApiPublicRValidateRoute: typeof ApiPublicRValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token/': {
      id: '/r/$token/'
      path: '/'
      fullPath: '/r/$token/'
      preLoaderRoute: typeof RTokenIndexRouteImport
      parentRoute: typeof RTokenRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/r/$token/$': {
      id: '/r/$token/$'
      path: '/$'
      fullPath: '/r/$token/$'
      preLoaderRoute: typeof RTokenSplatRouteImport
      parentRoute: typeof RTokenRoute
    }
    '/_authenticated/app/book-call': {
      id: '/_authenticated/app/book-call'
      path: '/app/book-call'
      fullPath: '/app/book-call'
      preLoaderRoute: typeof AuthenticatedAppBookCallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/api/public/r/validate': {
      id: '/api/public/r/validate'
      path: '/api/public/r/validate'
      fullPath: '/api/public/r/validate'
      preLoaderRoute: typeof ApiPublicRValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/state': {
      id: '/api/public/r/state'
      path: '/api/public/r/state'
      fullPath: '/api/public/r/state'
      preLoaderRoute: typeof ApiPublicRStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/save': {
      id: '/api/public/r/save'
      path: '/api/public/r/save'
      fullPath: '/api/public/r/save'
      preLoaderRoute: typeof ApiPublicRSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/complete': {
      id: '/api/public/r/complete'
      path: '/api/public/r/complete'
      fullPath: '/api/public/r/complete'
      preLoaderRoute: typeof ApiPublicRCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/capture': {
      id: '/api/public/r/capture'
      path: '/api/public/r/capture'
      fullPath: '/api/public/r/capture'
      preLoaderRoute: typeof ApiPublicRCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/admin/review': {
      id: '/_authenticated/app/admin/review'
      path: '/review'
      fullPath: '/app/admin/review'
      preLoaderRoute: typeof AuthenticatedAppAdminReviewRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/salescode/': {
      id: '/_authenticated/app/admin/salescode/'
      path: '/salescode'
      fullPath: '/app/admin/salescode/'
      preLoaderRoute: typeof AuthenticatedAppAdminSalescodeIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/audit/': {
      id: '/_authenticated/app/admin/audit/'
      path: '/audit'
      fullPath: '/app/admin/audit/'
      preLoaderRoute: typeof AuthenticatedAppAdminAuditIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/tools/$key/$': {
      id: '/_authenticated/app/tools/$key/$'
      path: '/app/tools/$key/$'
      fullPath: '/app/tools/$key/$'
      preLoaderRoute: typeof AuthenticatedAppToolsKeySplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/salescode/$ownerId': {
      id: '/_authenticated/app/admin/salescode/$ownerId'
      path: '/salescode/$ownerId'
      fullPath: '/app/admin/salescode/$ownerId'
      preLoaderRoute: typeof AuthenticatedAppAdminSalescodeOwnerIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/audit/$ownerId': {
      id: '/_authenticated/app/admin/audit/$ownerId'
      path: '/audit/$ownerId'
      fullPath: '/app/admin/audit/$ownerId'
      preLoaderRoute: typeof AuthenticatedAppAdminAuditOwnerIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminReviewRoute: typeof AuthenticatedAppAdminReviewRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
  AuthenticatedAppAdminAuditOwnerIdRoute: typeof AuthenticatedAppAdminAuditOwnerIdRoute
  AuthenticatedAppAdminSalescodeOwnerIdRoute: typeof AuthenticatedAppAdminSalescodeOwnerIdRoute
  AuthenticatedAppAdminAuditIndexRoute: typeof AuthenticatedAppAdminAuditIndexRoute
  AuthenticatedAppAdminSalescodeIndexRoute: typeof AuthenticatedAppAdminSalescodeIndexRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminReviewRoute: AuthenticatedAppAdminReviewRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
  AuthenticatedAppAdminAuditOwnerIdRoute:
    AuthenticatedAppAdminAuditOwnerIdRoute,
  AuthenticatedAppAdminSalescodeOwnerIdRoute:
    AuthenticatedAppAdminSalescodeOwnerIdRoute,
  AuthenticatedAppAdminAuditIndexRoute: AuthenticatedAppAdminAuditIndexRoute,
  AuthenticatedAppAdminSalescodeIndexRoute:
    AuthenticatedAppAdminSalescodeIndexRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppBookCallRoute: typeof AuthenticatedAppBookCallRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppToolsKeySplatRoute: typeof AuthenticatedAppToolsKeySplatRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppBookCallRoute: AuthenticatedAppBookCallRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppToolsKeySplatRoute: AuthenticatedAppToolsKeySplatRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RTokenRouteChildren {
  RTokenSplatRoute: typeof RTokenSplatRoute
  RTokenIndexRoute: typeof RTokenIndexRoute
}

const RTokenRouteChildren: RTokenRouteChildren = {
  RTokenSplatRoute: RTokenSplatRoute,
  RTokenIndexRoute: RTokenIndexRoute,
}

const RTokenRouteWithChildren =
  RTokenRoute._addFileChildren(RTokenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RTokenRoute: RTokenRouteWithChildren,
  ApiPublicRCaptureRoute: ApiPublicRCaptureRoute,
  ApiPublicRCompleteRoute: ApiPublicRCompleteRoute,
  ApiPublicRSaveRoute: ApiPublicRSaveRoute,
  ApiPublicRStateRoute: ApiPublicRStateRoute,
  ApiPublicRValidateRoute: ApiPublicRValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
